### ISSUE TITLE
Bug: Kinetic Sharpshooter/Onslaught Multiclass - Loses quiver charges per shot

### ISSUE THREAD

**Issue by SpencerMycek** [NosVladimir/KineticArchetypes#27]
Hello!
So, this definitely falls into a weird spot, since the game doesn't natively support multiclassing, but I was doing some testing.
(Toybox multiclassing)

It looks like onslaught blaster behaves weirdly with the Kinetic Quiver thing, where a single "attack" will use up more than one charge from the quiver. It's not necessarily 1 attack roll = 1 charge lost, but I believe you do lose more than the 1 I would expect for the entire onslaught blast

**Comment by NosVladimir** [comment]
Hi Spence, thanks for reporting! Unfortunately I haven't bought the second season pass so I can't test this at the moment. 

The way I've implemented the onslaught blast is by temporarily lowering the rank of the kinetic blast feature when using a blast upon OnEventAboutToTrigger(RuleCastSpell evt), then repeating the blast for corresponding times using custom RuleCastSpell, then reverting the rank when all repetitions are done. It could be that the new class has some kind of buff/feature/component in somewhere that listens to RuleCastSpell and checks if it's a kinetic blast of some kind and spends resources accordingly.

I've also heard that multi-archtyping Kinetic Sharpshooter and Onslaught Blaster will mean that each blast fired will benefit from all enchantments of the weapon, like bane, which boosts the damage by multiples. If that's really the case (I can't confirm on my own) then I guess as a design choice we may keep the extra resource-spending as a feature? I'd appreciate a lot if you could test more on that and post any findings here (but don't feel obliged to do so).

**Comment by SpencerMycek** [comment]
I'll do some testing once I get KEE working as I start playing through the game

If bane and stuff does apply multiple times, I guess it does make sense to keep the resource cost the way it is.

Thank you!

**Comment by Vannner013** [comment]
How do you make this multiclass? Even with multiple archetypes from toybox enabled, i cant pick kinetic sharpshooter with onslaught Blaster.

Also is this bug of spending multiple charges still happening?

Thank you for The amazing mod!

**Comment by NosVladimir** [comment]
> How do you make this multiclass? Even with multiple archetypes from toybox enabled, i cant pick kinetic sharpshooter with onslaught Blaster.
> 
> Also is this bug of spending multiple charges still happening?
> 
> Thank you for The amazing mod!

There's a mod called Multiple Archetypes that allows you to simultaneously choose archetypes that don't forgo the same base class features. I haven't bought any more DLCs so I can't test it myself. If Owlcat has updated the kinetic sharpshooter archetype such that it's now forgoing something in common to the onslaught blaster archetype, then by the rules (of tabletop and the Multiple Archetypes mod) they cannot be chosen at the same time. I'm not sure how ToyBox multiarchetype works.

**Comment by Vannner013** [comment]
It works The same way The standalone mod does, Shame it doesnt work anymore with onslaught Blaster =/

**Comment by NosVladimir** [comment]
> It works The same way The standalone mod does, Shame it doesnt work anymore with onslaught Blaster =/
> 
> Thank you 😁

I got other people's requests (and complaints) that kinetic sharpshooter can no longer be multi-archetyped with onslaught blaster, so I took a look and it appeared to be the update introducing a capstone for sharpshooter which also made sharpshooter drop supercharge, so it clashes with onslaught blaster which also drops supercharge.

I guess the logic of dropping supercharge is due to sharpshooter can't use gather power. Which makes sense. So it doesn't change anything if I add supercharge back... just for the sake of making multiarchetyping with onslaught blaster possible. I might do this (within this mod ofc) some time this week

**Comment by Vannner013** [comment]
> > It works The same way The standalone mod does, Shame it doesnt work anymore with onslaught Blaster =/
> > Thank you 😁
> 
> I got other people's requests (and complaints) that kinetic sharpshooter can no longer be multi-archetyped with onslaught blaster, so I took a look and it appeared to be the update introducing a capstone for sharpshooter which also made sharpshooter drop supercharge, so it clashes with onslaught blaster which also drops supercharge.
> 
> I guess the logic of dropping supercharge is due to sharpshooter can't use gather power. Which makes sense. So it doesn't change anything if I add supercharge back... just for the sake of making multiarchetyping with onslaught blaster possible. I might do this (within this mod ofc) some time this week

Sorry The late reply! Could you do that? Would Love to make lann a kinetic sharpshooter + onslaught Blaster 🙏

I'm having so much fun with The kinetic lancer 😁

Thanks for The work!

**Comment by NosVladimir** [comment]
@SpencerMycek Hey Spence, is this issue still relevant?

**Comment by SpencerMycek** [comment]
I don’t think so. I think we’re all good now
